# Generated by Django 3.0.5 on 2020-11-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_auto_20201119_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
